AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 40

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 300

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

Style/AsciiComments:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Enabled: false

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: Keywords.
# Keywords: TODO, FIXME, OPTIMIZE, HACK, REVIEW
Style/CommentAnnotation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Cop supports --auto-correct.
Style/SelfAssignment:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
# SupportedStyles: space, no_space
Style/SpaceInsideBlockBraces:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Style/AlignHash:
  Enabled: false

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false
